import json, uuid
from pathlib import Path

with open('kicad_pcb_generator.py', 'w', encoding='utf-8') as f:
    f.write('"""KiCad PCB Generator - Uses real footprint data from KiCad library"""\n')
    f.write('import json, uuid, logging\n')
    f.write('from pathlib import Path\n')
    f.write('try:\n')
    f.write('    from footprint_parser import get_footprint_parser\n')
    f.write('    _fp = get_footprint_parser()\n')
    f.write('except Exception:\n')
    f.write('    _fp = None\n')
    f.write('\n')
    f.write('def _gp(f):\n')
    f.write('    if not _fp: return None\n')
    f.write('    try:\n')
    f.write('        d = _fp.find_footprint(f)\n')
    f.write('        return d.get("pads") if d else None\n')
    f.write('    except Exception: return None\n')
    f.write('\n')
    f.write('def gu(): return str(uuid.uuid4())\n')
    f.write('\n')
    f.write('def cf(l, c, x, y):\n')
    f.write('    f = c.get("footprint", "R_SMD:R_0603")\n')
    f.write('    r = c.get("reference", "R")\n')
    f.write('    v = c.get("name", "R")\n')
    f.write('    if ":" in f:\n')
    f.write('        fp_lib, f_name = f.split(":", 1)\n')
    f.write('    else:\n')
    f.write('        fp_lib, f_name = "R_SMD", f\n')
    f.write('    l.append(f"\t(footprint \\"{f}\\"")\n')
    f.write('    l.append("\t\t(layer \\"F.Cu\\")")\n')
    f.write('    l.append(f"\t\t(uuid \\"{gu()}\\"")\n')
    f.write('    l.append(f"\t\t(at {x:.2f} {y:.2f})")\n')
    f.write('    l.append(f"\t\t(descr \\"{v}\\"")\n')
    f.write('    l.append(f"\t\t(property \\"Reference\\" \\"{r}\\"")\n')
    f.write('    l.append("\t\t\t(at 0 0 0)")\n')
    f.write('    l.append("\t\t\t(layer \\"F.SilkS\\")")\n')
    f.write('    l.append(f"\t\t\t(uuid \\"{gu()}\\"")\n')
    f.write('    l.append("\t\t\t(effects")\n')
    f.write('    l.append("\t\t\t\t(font")\n')
    f.write('    l.append("\t\t\t\t\t(size 1 1)")\n')
    f.write('    l.append("\t\t\t\t\t(thickness 0.15)")\n')
    f.write('    l.append("\t\t\t\t)")\n')
    f.write('    l.append("\t\t\t)")\n')
    f.write('    l.append("\t\t)")\n')
    f.write('    l.append(f"\t\t(property \\"Value\\" \\"{v}\\"")\n')
    f.write('    l.append("\t\t\t(at 0 0 0)")\n')
    f.write('    l.append("\t\t\t(layer \\"F.Fab\\")")\n')
    f.write('    l.append(f"\t\t\t(uuid \\"{gu()}\\"")\n')
    f.write('    l.append("\t\t\t(effects")\n')
    f.write('    l.append("\t\t\t\t(font")\n')
    f.write('    l.append("\t\t\t\t\t(size 1 1)")\n')
    f.write('    l.append("\t\t\t\t\t(thickness 0.15)")\n')
    f.write('    l.append("\t\t\t\t)")\n')
    f.write('    l.append("\t\t\t)")\n')
    f.write('    l.append("\t\t)")\n')
    f.write('    rp = _gp(f)\n')
    f.write('    if rp:\n')
    f.write('        for p in rp:\n')
    f.write('            n = p.get("number", "1")\n')
    f.write('            t = p.get("type", "smd")\n')
    f.write('            sh = p.get("shape", "rect")\n')
    f.write('            pos = p.get("position", {"x": 0, "y": 0})\n')
    f.write('            sz = p.get("size", {"x": 1, "y": 1})\n')
    f.write('            ly = p.get("layers", ["F.Cu", "F.Paste", "F.Mask"])\n')
    f.write('            ls = " ".join([f"\\"{l}\\"" for l in ly])\n')
    f.write('            if t == "smd":\n')
    f.write('                l.append(f"\t\t(pad \\"{n}\\" smd {sh} (at {pos[\'x\']:.3f} {pos[\'y\']:.3f}) (size {sz[\'x\']:.3f} {sz[\'y\']:.3f}) (layers {ls}))")\n')
    f.write('            else:\n')
    f.write('                l.append(f"\t\t(pad \\"{n}\\" thru_hole circle (at {pos[\'x\']:.3f} {pos[\'y\']:.3f}) (size {sz[\'x\']:.3f} {sz[\'y\']:.3f}) (drill 0.4) (layers *.Cu F.Mask F.SilkS))")\n')
    f.write('    else:\n')
    f.write('        if "DIP" in f_name and "8" in f_name:\n')
    f.write('            for px, py, n in [(-3.81,-3.81,1),(-3.81,-1.27,2),(-3.81,1.27,3),(-3.81,3.81,4),(3.81,3.81,5),(3.81,1.27,6),(3.81,-1.27,7),(3.81,-3.81,8)]:\n')
    f.write('                l.append(f"\t\t(pad {n} thru_hole circle (at {px:.2f} {py:.2f}) (size 0.6 0.6) (drill 0.4) (layers *.Cu F.Mask F.SilkS)")\n')
    f.write('        elif "0603" in f_name or "1608" in f_name or "Resistor" in fp_lib or "R_" in f_name:\n')
    f.write('            l.append("\t\t(pad 1 smd rect (at -0.8 0) (size 0.9 0.8) (layers F.Cu F.Paste F.Mask))")\n')
    f.write('            l.append("\t\t(pad 2 smd rect (at 0.8 0) (size 0.9 0.8) (layers F.Cu F.Paste F.Mask))")\n')
    f.write('        elif "LED" in f_name or "LED" in fp_lib:\n')
    f.write('            l.append("\t\t(pad 1 smd rect (at -0.7 0) (size 0.6 0.6) (layers F.Cu F.Paste F.Mask))")\n')
    f.write('            l.append("\t\t(pad 2 smd rect (at 0.7 0) (size 0.6 0.6) (layers F.Cu F.Paste F.Mask))")\n')
    f.write('        elif "Capacitor" in fp_lib or "C_" in f_name or "CAP" in f_name:\n')
    f.write('            l.append("\t\t(pad 1 smd rect (at -0.8 0) (size 0.9 0.8) (layers F.Cu F.Paste F.Mask))")\n')
    f.write('            l.append("\t\t(pad 2 smd rect (at 0.8 0) (size 0.9 0.8) (layers F.Cu F.Paste F.Mask))")\n')
    f.write('        else:\n')
    f.write('            l.append("\t\t(pad 1 smd rect (at -0.8 0) (size 0.9 0.8) (layers F.Cu F.Paste F.Mask))")\n')
    f.write('            l.append("\t\t(pad 2 smd rect (at 0.8 0) (size 0.9 0.8) (layers F.Cu F.Paste F.Mask))")\n')
    f.write('    l.append("\t)")\n')

print('Part 1 done')
